---
- include: ./install_packages.yml

- name: checking that RVM is installed
  stat:
    path: "{{rvm.init_script}}"
  ignore_errors: True
  register: rvm_install_result

- include: ./install_rvm.yml
  when: rvm_install_result.stat.exists != true

- include: ./update_rvm.yml
  when: rvm.auto_update_rvm and rvm_install_result.stat.exists == true

- include: ./select_ruby.yml

- include: ./install_ruby.yml
  when: rvm_select_ruby_version|failed
